# Generated by Django 4.0.1 on 2023-06-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='admin',
            field=models.OneToOneField(default=1111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficheachatcommandefournisseur'),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fournisseur'),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_rf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursfournisseur',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_rc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_rc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='retoursclient',
            name='vente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retours_client', to='core.ficheventeclient'),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depot'),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_vente_client', to='core.produit'),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.ficheventeclient'),
        ),
        migrations.AddField(
            model_name='produitsretourfournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retour_fournisseur', to='core.produit'),
        ),
        migrations.AddField(
            model_name='produitsretourfournisseur',
            name='retour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.retoursfournisseur'),
        ),
        migrations.AddField(
            model_name='produitsretourclient',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_retour_client', to='core.produit'),
        ),
        migrations.AddField(
            model_name='produitsretourclient',
            name='retour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.retoursclient'),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.ficheachatcommandefournisseur'),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.depot'),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_achat_fournisseur', to='core.produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.familleproduit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.marqueproduit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficheachatcommandefournisseur'),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fournisseur'),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_pf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_pf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payementfournisseur',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='achat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ficheachatcommandefournisseur'),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='modilfie_par',
            field=models.ForeignKey(default=1111, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_pc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_pc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payementclient',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='fraisgenerales',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='fraisgenerales',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_fg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraisgenerales',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_fg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraisgenerales',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='fraisgenerales',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typefg'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_vc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='fichedebit',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='fichedebit',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_deb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichedebit',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_deb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichedebit',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selling_point_fd', to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='fichecredit',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='fichecredit',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichecredit',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichecredit',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_point_fc', to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.fournisseur'),
        ),
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='modifie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifie_par_fac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='saisie_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_par_fac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='selling_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='depot',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='produits', to='core.Produit'),
        ),
        migrations.AddField(
            model_name='depot',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='client',
            name='saisie_par',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='clarque',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='caisse',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_point_caisse', to='core.sellingpoint'),
        ),
        migrations.AddField(
            model_name='avaries',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produit'),
        ),
        migrations.AddField(
            model_name='avaries',
            name='selling_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint'),
        ),
    ]
