# Generated by Django 4.0.1 on 2023-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
