# Generated by Django 4.0.1 on 2023-05-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_revendeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qtte',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
