# Generated by Django 4.0.1 on 2023-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Al',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='NIF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
