# Generated by Django 4.0.1 on 2023-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produit_prix_vente_revendeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_autre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
