# Generated by Django 4.0.1 on 2023-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produit_prix_vente_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheventeclient',
            name='numero',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
