# Generated by Django 4.0.1 on 2023-06-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_al_client_nif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payementclient',
            name='achat',
        ),
    ]
