# Generated by Django 4.0.1 on 2023-06-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ficheventeclient_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheventeclient',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produitventeclient',
            name='numero_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
