# Generated by Django 4.0.1 on 2023-06-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payementclient_modilfie_par_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payementclient',
            name='date',
        ),
    ]
