# Generated by Django 4.0.1 on 2023-06-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_payementclient_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementclient',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
