# Generated by Django 4.0.1 on 2023-06-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vendeur_admin_alter_vendeur_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='family_situation',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='identity_num',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='img',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='phone_number_1',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='phone_number_2',
        ),
    ]
