# Generated by Django 4.0.1 on 2023-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_produitventeclient_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheventeclient',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='ficheventeclient',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='prix_autre_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='prix_datail_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='prix_gros_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='produit_article',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='produit_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='produit_unite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitventeclient',
            name='total_prix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
