# Generated by Django 4.0.1 on 2023-07-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ficheventeclient_subtotal_ficheventeclient_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitventeclient',
            old_name='prix_datail_produit',
            new_name='prix_detail_produit',
        ),
    ]
