# Generated by Django 4.0.1 on 2023-07-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_caisse_ville_remove_caisse_wilaya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitachatcommandefournisseur',
            name='unit',
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='prix_autre_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='prix_detail_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='prix_gros_produit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='produit_article',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='produit_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='produit_unite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produitachatcommandefournisseur',
            name='total_prix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='date_de_fabrication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='date_dexpiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_achat_fournisseur', to='core.produit'),
        ),
    ]
