# Generated by Django 4.0.1 on 2023-07-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_produitachatcommandefournisseur_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depot'),
        ),
    ]
