# Generated by Django 4.0.1 on 2023-07-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_produitachatcommandefournisseur_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.caisse'),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='mode_reglement',
            field=models.CharField(blank=True, choices=[('A terme', 'A terme'), ('Espece', 'Espece'), ('Virement', 'Virement'), ('chèque', 'chèque')], default='Espece', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='montantregfour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheachatcommandefournisseur',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
