# Generated by Django 4.0.1 on 2023-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ficheachatcommandefournisseur_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitachatcommandefournisseur',
            name='numero_lot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
