# Generated by Django 4.0.1 on 2023-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_ficheachatcommandefournisseur_tva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
