# Generated by Django 4.0.1 on 2023-07-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ficheachatcommandefournisseur_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payementfournisseur',
            name='achat',
        ),
    ]
