# Generated by Django 4.0.1 on 2023-07-15 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_produitventeclient_prix_achat_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaries',
            name='saisie_le',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
