# Generated by Django 4.0.1 on 2023-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_avaries_saisie_le'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unit',
            field=models.CharField(choices=[('bedon', 'bedon'), ('u', 'u'), ('Kg', 'Kg'), ('sac', 'sac'), ('g', 'g'), ('l', 'l'), ('m', 'm'), ('m2', 'm2')], default=1, max_length=20),
        ),
    ]
