# Generated by Django 4.0.1 on 2023-07-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_produit_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaries',
            name='depot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.depot'),
            preserve_default=False,
        ),
    ]
