# Generated by Django 4.0.1 on 2023-07-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_avaries_modifie_par_avaries_modilfié_le_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_lot', models.IntegerField(blank=True, null=True)),
                ('total_prix', models.IntegerField(blank=True, null=True)),
                ('prix_detail_produit', models.IntegerField(blank=True, null=True)),
                ('prix_gros_produit', models.IntegerField(blank=True, null=True)),
                ('prix_autre_produit', models.IntegerField(blank=True, null=True)),
                ('produit_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('date_de_fabrication', models.DateField(blank=True, null=True)),
                ('date_dexpiration', models.DateField(blank=True, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produitsDepot', to='core.depot')),
                ('produit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depotProduit', to='core.produit')),
                ('selling_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sellingpoint')),
            ],
        ),
    ]
