# Generated by Django 4.0.1 on 2023-07-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_avaries_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitdepot',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
