# Generated by Django 4.0.1 on 2023-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_produitdepot_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitdepot',
            name='produit_article',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
