# Generated by Django 4.0.1 on 2023-07-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_produitachatcommandefournisseur_prix_achat_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payementclient',
            name='numero',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
