# Generated by Django 4.0.1 on 2023-07-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_fraisgenerales_numero_payementfournisseur_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheachatcommandefournisseur',
            name='numero',
        ),
    ]
