# Generated by Django 4.0.1 on 2023-07-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_ficheachatcommandefournisseur_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheachatcommandefournisseur',
            name='numero',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
